### ISSUE TITLE
这个后处理的库似乎和那个动态天空的库不兼容

### ISSUE THREAD

**Issue by ghost** [uinosoft/t3d-effect-composer#2]
在场景中加入动态天空以后， 加载的glb模型无法显示，
不加入动态天空又可以显示

**Comment by ghost** [comment]
我使用的forwardrender进行的渲染

**Comment by ghost** [comment]
似乎是因为开启了灯光的产生阴影的功能导致的：
		const sunLight = new t3d.DirectionalLight();
		sunLight.intensity = 1;
		// sunLight.castShadow = true;
		// sunLight.shadow.windowSize = 15;
		scene.add(sunLight);


		
		const moonLight = new t3d.DirectionalLight();
		// moonLight.castShadow = true;
		// moonLight.shadow.windowSize = 15;
		scene.add(moonLight);

这样注销掉就可以显示了， 但是如果我想产生阴影怎么办

**Comment by ghost** [comment]
@shawn0326   需要帮助！

**Comment by shawn0326** [comment]
是否有报错信息可以帮助定位问题？不过建议如果使用后期库的话，不要使用ForwardRenderer，直接使用Renderer。猜测有种可能是没有执行ShadowMapPass的渲染，后期库是不负责执行阴影贴图渲染的，需要手动调用。具体可以参考本库中自带的示例，尤其是带阴影效果的示例。

**Comment by ghost** [comment]
> 是否有报错信息可以帮助定位问题？不过建议如果使用后期库的话，不要使用ForwardRenderer，直接使用Renderer。猜测有种可能是没有执行ShadowMapPass的渲染，后期库是不负责执行阴影贴图渲染的，需要手动调用。具体可以参考本库中自带的示例，尤其是带阴影效果的示例。

我试试看， 但在动态天气和后处理一起使用的时候 ， 感觉会出现一些不兼容的情况，  显示效果不是我想要的。 控制台并没有报错

**Comment by shawn0326** [comment]
https://github.com/shawn0326/t3d-scene-demo
这里有一个例子使用了后期库与动态天空，也许可以参考

**Comment by ghost** [comment]
> https://github.com/shawn0326/t3d-scene-demo 这里有一个例子使用了后期库与动态天空，也许可以参考

大佬牛皮
